server:
  port: 8671
eureka:
  instance:
    hostname: eureka01
  client:
    fetch-registry: false
 #   register-with-eureka: false
    service-url:
      defaultZone: http://eureka02:8672/eureka,http://eureka03:8673/eureka
